name: Setup
runs:
  using: "composite"
  steps:
    - name: Cache STM32CubeMX generated code
      id: cache-stm32cubemx
      uses: actions/cache@v4
      env:
        cache-key: cache-stm32cubemx-${{ hashFiles('./boards/CAVeBoard/generated/CAVeBoard.ioc', './boards/CAVeBoard/generated/CAVeBoard.script') }}
        cache-base-path: ./boards/CAVeBoard/generated
        startup-file: startup_stm32f407xx.s
        linker-script: stm32f407zgtx_flash.ld
      with:
        path: |
          ${{ env.cache-base-path }}/cmake
          ${{ env.cache-base-path }}/Core
          ${{ env.cache-base-path }}/Drivers
          ${{ env.cache-base-path }}/.mxproject
          ${{ env.cache-base-path }}/CMakeLists.txt
          ${{ env.cache-base-path }}/CMakePresets.json
          ${{ env.cache-base-path }}/${{ env.startup-file }}
          ${{ env.cache-base-path }}/${{ env.linker-script }}
        key: ${{ env.cache-key }}
        restore-keys: ${{ env.cache-key }}
    - name: STM32CubeMX Generate Code
      if: ${{ steps.cache-stm32cubemx.outputs.cache-hit != 'true' }}
      uses: docker://d3lta12/stm32cubemx-stm32f4:v6.13.0
      with:
        args: /bin/bash -c "cd boards/CAVeBoard/generated && /opt/STM32CubeMX/jre/bin/java -jar /opt/STM32CubeMX/STM32CubeMX -q CAVeBoard.script"
    - name: Generate CAVeTalk Protobufs
      run: external/CAVeTalk/tools/nanopb/generate.sh
      shell: sh
    - name: Cache CMake files
      id: cache-cmake
      uses: actions/cache@v4
      env:
        cache-key: cache-cmake-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
      with:
        path: ./build
        key: ${{ env.cache-key }}
        restore-keys: ${{ env.cache-key }}
    - name: Generate CMake cache
      if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
      run: cmake --preset CAVeBoard_Release
      shell: sh