name: Setup
runs:
  using: "composite"
  steps:
    # TODO cache STM32CubeMX generated code, re-build cache on ioc changes
    - name: STM32CubeMX Generate Code
      uses: docker://d3lta12/stm32cubemx-stm32f4
      with:
        args: /bin/bash -c "cd bsp/boards/CAVeBoard/generated && /opt/STM32CubeMX/jre/bin/java -jar /opt/STM32CubeMX/STM32CubeMX -q CAVeBoard.script"
    - name: Generate CAVeTalk Protobufs
      run: external/CAVeTalk/tools/nanopb/generate.sh
      shell: sh
    - name: Cache CMake files
      id: cache-cmake
      uses: actions/cache@v4
      env:
        cache-name: cache-cmake
      with:
        path: ./build
        key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
    - name: Generate CMake cache
      if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
      run: cmake --preset CAVeBoard_Debug
      shell: sh