services:
  arm-build:
    build:
      context: ./arm-build
      dockerfile: Dockerfile
    volumes:
      - ./../../:/CAVeware/
    working_dir: /CAVeware
  stm32f4:
    build:
      context: ./stm32cubemx
      dockerfile: Dockerfile
    volumes:
      - ./../../:/CAVeware/
    working_dir: /CAVeware