name: Continuous Deployment Workflow

on:
  push:
    tags:
      - "v*"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  release:
    runs-on: ubuntu-latest
    # if: >
    #   github.event.workflow_run.conclusion == 'success' &&
    #   startsWith(github.ref, 'refs/tags/')
    needs: ci    
    steps:
      - name: Debug
        run: |
          echo "${{ needs.call-ci.outputs.tag_name }} ${{ needs.call-ci.outputs.tag_ref }}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Create pre-release
        if: ${{ contains(github.ref_name, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --title="${tag#v}" \
              --generate-notes \
              --latest=false
              --prerelease
      - name: Create release
        if: ${{ contains(github.ref_name, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --title="${tag#v}" \
              --generate-notes \
              --latest=true
      # TODO verify status checks
      # - name: Upload build
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./your_artifact.zip
      #     asset_name: your_artifact.zip
      #     asset_content_type: application/zip